apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-timestamper-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger-timestamper-dep
  template:
    metadata:
      labels:
        app: logger-timestamper-dep
    spec:
      volumes:
        - name: timestamp
          emptyDir: {}
        - name: pingpong-count
          persistentVolumeClaim:
            claimName: pingpong-claim
      containers:
        - name: timestamper
          image: heniko/timestamper:v2.1
          volumeMounts:
            - name: timestamp
              mountPath: /usr/src/app/files
        - name: pingpong
          image: heniko/pingpong:v2.1
          volumeMounts:
            - mountPath: /usr/src/app/pingpong-count
              name: pingpong-count
        - name: logger
          image: heniko/logger:v2.3
          env:
            - name: PORT
              value: "3001"
          volumeMounts:
            - name: timestamp
              mountPath: /usr/src/app/files
            - name: pingpong-count
              mountPath: /usr/src/app/pingpong-count
