apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: todo-namespace
  name: todo-ingress
  labels:
    name: todo-ingress
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: todo-server-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-web-svc
                port:
                  number: 80
