apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: logger-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-dep
  template:
    metadata:
      labels:
        app: pingpong-dep
    spec:
      containers:
        - name: pingpong-app
          image: heniko/pingpong:v2.4
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: logger-db-secret
                  key: DATABASE_URL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-timestamper-dep
  namespace: logger-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger-timestamper-dep
  template:
    metadata:
      labels:
        app: logger-timestamper-dep
    spec:
      volumes:
        - name: timestamp
          emptyDir: {}
      containers:
        - name: timestamper
          image: heniko/timestamper:v2.1
          volumeMounts:
            - name: timestamp
              mountPath: /usr/src/app/files
        - name: logger
          image: heniko/logger:v2.8
          env:
            - name: PORT
              value: "3001"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logger-configmap
                  key: message
          volumeMounts:
            - name: timestamp
              mountPath: /usr/src/app/files
