apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: todo-namespace
  name: daily-todo-job
spec:
  schedule: 0 0 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: daily-todo-job
              image: heniko/todo-daily-job:v1.1
              env:
                - name: API_URL
                  value: "http://todo-server-svc:2346/api/todos"
          restartPolicy: OnFailure
