apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web
  namespace: todo-namespace
spec:
  selector:
    matchLabels:
      app: todo-web
  template:
    metadata:
      labels:
        app: todo-web
    spec:
      containers:
        - name: todo-web
          image: gcr.io/PROJECT_ID/IMAGE
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 3000
